// BattleBros — seed data
// 8 fighters, venues, weapons. Grounded comedy traits.

const FIGHTERS = [
  {
    id: "marcus",
    name: "MARCUS",
    handle: "@marcus_p",
    unlocked: true,
    wins: 7, losses: 3,
    palette: { skin: "#e8b89a", hair: "#3a2418", shirt: "#2563eb", accent: "#fbbf24" },
    accessories: ["bucket-hat", "golf-club"],
    build: "lanky",
    traits: [
      { text: "always wears a bucket hat", weight: 9, by: "dev", up: 6 },
      { text: "bad at golf, won't admit it", weight: 8, by: "kira", up: 5 },
      { text: "owns 14 different hot sauces", weight: 6, by: "ben", up: 3 },
      { text: "argues about pizza toppings", weight: 5, by: "sam", up: 4 },
      { text: "claims he can dunk", weight: 7, by: "ash", up: 5 },
      { text: "cries during pixar credits", weight: 4, by: "kira", up: 7 },
      { text: "talks loudly in libraries", weight: 5, by: "dev", up: 2 },
      { text: "calls everyone 'chief'", weight: 6, by: "ben", up: 4 },
      { text: "competitive at mini golf", weight: 5, by: "sam", up: 3 },
      { text: "bench presses 165", weight: 4, by: "ash", up: 1 },
    ],
    weapon: "9-iron",
    venue: "costco",
    bestTagline: "He came for the rotisserie. He left a legend.",
  },
  {
    id: "kira",
    name: "KIRA",
    handle: "@kira.exe",
    unlocked: true,
    wins: 9, losses: 2,
    palette: { skin: "#d8a07a", hair: "#1a1a1a", shirt: "#ec4899", accent: "#22d3ee" },
    accessories: ["headphones", "energy-drink"],
    build: "compact",
    traits: [
      { text: "lives on cold brew", weight: 10, by: "marcus", up: 8 },
      { text: "wins every argument by exhausting you", weight: 9, by: "dev", up: 9 },
      { text: "deceptively strong for her size", weight: 8, by: "ben", up: 6 },
      { text: "DJs at 2am unprompted", weight: 6, by: "sam", up: 4 },
      { text: "remembers everything you've said", weight: 8, by: "ash", up: 7 },
      { text: "can sleep anywhere", weight: 5, by: "marcus", up: 3 },
      { text: "drives like she's in mario kart", weight: 7, by: "ben", up: 5 },
      { text: "won a hot dog eating contest in 2021", weight: 4, by: "dev", up: 6 },
    ],
    weapon: "monster-can",
    venue: "ikea",
    bestTagline: "Caffeinated. Vindicated. Undefeated.",
  },
  {
    id: "dev",
    name: "DEV",
    handle: "@devvy",
    unlocked: true,
    wins: 5, losses: 5,
    palette: { skin: "#a87454", hair: "#0a0a0a", shirt: "#10b981", accent: "#f59e0b" },
    accessories: ["glasses", "laptop"],
    build: "average",
    traits: [
      { text: "writes code at parties", weight: 8, by: "kira", up: 6 },
      { text: "can name every star wars ship", weight: 7, by: "ben", up: 4 },
      { text: "vegan but not annoying about it", weight: 5, by: "sam", up: 5 },
      { text: "secretly a great cook", weight: 6, by: "marcus", up: 7 },
      { text: "pacifist until provoked", weight: 9, by: "ash", up: 8 },
      { text: "knows kung fu (allegedly)", weight: 5, by: "kira", up: 2 },
      { text: "owns 3 mechanical keyboards", weight: 4, by: "ben", up: 3 },
    ],
    weapon: "laptop",
    venue: "denny's",
    bestTagline: "The quiet ones type the loudest.",
  },
  {
    id: "ben",
    name: "BEN",
    handle: "@bigben",
    unlocked: true,
    wins: 11, losses: 1,
    palette: { skin: "#c89175", hair: "#5c3a20", shirt: "#ef4444", accent: "#fbbf24" },
    accessories: ["beard", "flannel"],
    build: "tank",
    traits: [
      { text: "actually a giant", weight: 10, by: "dev", up: 9 },
      { text: "gentle until you touch his truck", weight: 9, by: "kira", up: 8 },
      { text: "can grill in any weather", weight: 7, by: "marcus", up: 6 },
      { text: "loves dolly parton", weight: 6, by: "sam", up: 7 },
      { text: "snapped a kayak in half once", weight: 8, by: "ash", up: 9 },
      { text: "calls his mom every sunday", weight: 5, by: "kira", up: 6 },
      { text: "owns 4 different axes", weight: 6, by: "marcus", up: 4 },
    ],
    weapon: "ikea-shelf",
    venue: "homedepot",
    bestTagline: "He grills. He grins. He wins.",
  },
  {
    id: "sam",
    name: "SAM",
    handle: "@samiam",
    unlocked: true,
    wins: 6, losses: 4,
    palette: { skin: "#e6c4a8", hair: "#d97706", shirt: "#8b5cf6", accent: "#ec4899" },
    accessories: ["fanny-pack", "skateboard"],
    build: "wiry",
    traits: [
      { text: "skates everywhere, even to weddings", weight: 8, by: "marcus", up: 7 },
      { text: "trash talks while losing", weight: 9, by: "ben", up: 8 },
      { text: "knows every diner in a 50mi radius", weight: 6, by: "dev", up: 5 },
      { text: "doesn't believe in jackets", weight: 7, by: "kira", up: 6 },
      { text: "dated a magician once", weight: 5, by: "ash", up: 8 },
      { text: "lightning fast, nothing else", weight: 8, by: "ben", up: 6 },
      { text: "carries a fanny pack of weird candy", weight: 6, by: "marcus", up: 5 },
    ],
    weapon: "skateboard",
    venue: "denny's",
    bestTagline: "Slipped. Got back up. Slipped again. Won.",
  },
  {
    id: "ash",
    name: "ASH",
    handle: "@ashfromacct",
    unlocked: true,
    wins: 4, losses: 6,
    palette: { skin: "#bd8866", hair: "#9333ea", shirt: "#06b6d4", accent: "#f59e0b" },
    accessories: ["earrings", "skateboard"],
    build: "average",
    traits: [
      { text: "former gymnast, current accountant", weight: 9, by: "kira", up: 8 },
      { text: "can do a backflip on demand", weight: 8, by: "marcus", up: 9 },
      { text: "afraid of geese, won't talk about it", weight: 7, by: "dev", up: 9 },
      { text: "hosts board game nights with 14 rules", weight: 6, by: "ben", up: 5 },
      { text: "purple hair every season", weight: 5, by: "sam", up: 4 },
      { text: "has thrown up on a roller coaster", weight: 4, by: "marcus", up: 7 },
    ],
    weapon: "monopoly-board",
    venue: "ikea",
    bestTagline: "Ledger balanced. Opponent flattened.",
  },
  {
    id: "tony",
    name: "TONY",
    handle: "@tonybaloney",
    unlocked: false,
    wins: 0, losses: 0,
    palette: { skin: "#d4a07c", hair: "#1a1a1a", shirt: "#fbbf24", accent: "#ef4444" },
    accessories: ["chain", "sunglasses"],
    build: "stocky",
    traits: [
      { text: "shows up 2 hours late", weight: 8, by: "ben", up: 7 },
      { text: "has 11 cousins, all named tony", weight: 9, by: "kira", up: 9 },
    ],
    weapon: null,
    venue: null,
    bestTagline: null,
  },
  {
    id: "remy",
    name: "REMY",
    handle: "@remyremy",
    unlocked: false,
    wins: 0, losses: 0,
    palette: { skin: "#a16040", hair: "#fbbf24", shirt: "#22d3ee", accent: "#ec4899" },
    accessories: ["beanie"],
    build: "wiry",
    traits: [
      { text: "won't shut up about pickleball", weight: 7, by: "marcus", up: 5 },
      { text: "owns a llama (lives in colorado)", weight: 9, by: "dev", up: 9 },
      { text: "vegan one week, all-beef the next", weight: 6, by: "sam", up: 4 },
    ],
    weapon: null,
    venue: null,
    bestTagline: null,
  },
];

const VENUES = [
  { id: "costco", name: "COSTCO PARKING LOT", blurb: "Concrete arena. Free samples litter the field.", mods: ["+CARTS", "+SAMPLES", "-VISIBILITY"], color: "#3b82f6" },
  { id: "ikea", name: "IKEA SHOWROOM", blurb: "Endless maze of fake apartments. No exit in sight.", mods: ["+FURNITURE", "-NAVIGATION", "+MEATBALLS"], color: "#fbbf24" },
  { id: "denny's", name: "DENNY'S AT 3AM", blurb: "Fluorescent purgatory. Coffee is free, regret is not.", mods: ["+SYRUP", "+WITNESSES", "-SOBRIETY"], color: "#ec4899" },
  { id: "homedepot", name: "HOME DEPOT GARDEN CTR.", blurb: "Mulch underfoot. Lumber overhead. Bees everywhere.", mods: ["+LUMBER", "+BEES", "-CEILING"], color: "#10b981" },
  { id: "chuck", name: "CHUCK E. CHEESE", blurb: "Animatronic eyes follow you. Skee-ball judges all.", mods: ["+TICKETS", "+CHEESE", "-DIGNITY"], color: "#a855f7" },
  { id: "trader", name: "TRADER JOE'S, SUNDAY", blurb: "Cart-on-cart violence. Hawaiian shirts as armor.", mods: ["+CARTS", "+SAMPLES", "-MOBILITY"], color: "#ef4444" },
];

const WEAPONS = [
  { id: "9-iron", name: "BENT 9-IRON", blurb: "Found in a creek. Has seen things.", mods: ["+REACH", "+SHAME", "-ACCURACY"], color: "#fbbf24" },
  { id: "monster-can", name: "WARM MONSTER CAN", blurb: "Half-full. Shaken. Volatile.", mods: ["+CAFFEINE", "+FIZZ", "-GRIP"], color: "#22d3ee" },
  { id: "laptop", name: "2017 MACBOOK PRO", blurb: "Battery swollen. Keyboard sticky. Lethal.", mods: ["+WEIGHT", "+REGRET", "-WARRANTY"], color: "#10b981" },
  { id: "ikea-shelf", name: "UNASSEMBLED BILLY", blurb: "Six feet of pressed wood. Allen key included.", mods: ["+REACH", "+SPLINTERS", "-PORTABILITY"], color: "#ef4444" },
  { id: "skateboard", name: "WORN SKATE DECK", blurb: "Grip tape gone. Trucks loose. Still rolls.", mods: ["+SPEED", "+STYLE", "-CONTROL"], color: "#8b5cf6" },
  { id: "monopoly-board", name: "MONOPOLY BOARD", blurb: "Lost friendships baked in. Edges sharp.", mods: ["+RAGE", "+PAPER CUTS", "-FUN"], color: "#ec4899" },
  { id: "noodle", name: "POOL NOODLE", blurb: "Looks innocent. Wielded with intent.", mods: ["+REACH", "+CONFUSION", "-DAMAGE"], color: "#f97316" },
  { id: "frypan", name: "CAST IRON SKILLET", blurb: "Seasoned for 14 years. Heavier than guilt.", mods: ["+IMPACT", "+SEASONING", "-SPEED"], color: "#71717a" },
];

const PAST_FIGHTS = [
  { id: 1, a: "marcus", b: "ben", winner: "ben", venue: "homedepot", weaponA: "9-iron", weaponB: "ikea-shelf", tagline: "He came for the rotisserie. He left a legend.", date: "Apr 18" },
  { id: 2, a: "kira", b: "dev", winner: "kira", venue: "denny's", weaponA: "monster-can", weaponB: "laptop", tagline: "Caffeinated. Vindicated. Undefeated.", date: "Apr 11" },
  { id: 3, a: "sam", b: "ash", winner: "sam", venue: "ikea", weaponA: "skateboard", weaponB: "monopoly-board", tagline: "Slipped. Got back up. Slipped again. Won.", date: "Apr 04" },
];

window.BB_DATA = { FIGHTERS, VENUES, WEAPONS, PAST_FIGHTS };
